typography_spectrum: 0.54742
color:
  brandColors:
    - '#000000'
    - '#ff0000'
    - '#006600'
    - '#ff9f00'
    - '#fffbd4'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.36641
analytics:
  google: null
  facebook: null
  twitter: null
name: Webdude
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Mocks Aren't Stubs
    id: 20dd7e62-e29c-4b74-a524-bccb548f0842
    type: content
favicon: null
title: Webdudes Techblog
purpose: []
