name: Webdude
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54742
title: Webdudes Techblog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000201'
    - '#ffffff'
    - '#89a7a5'
    - '#01515c'
    - '#4c8691'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
