name: Webdude
favicon: null
layout_spectrum: 0.5535
typography_spectrum: 0.54742
title: Webdudes Techblog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff0000'
    - '#006600'
    - '#ff9f00'
    - '#fffbd4'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
